### ISSUE TITLE
Allow specific overrides

### ISSUE THREAD

**Issue by jwest-rms** [charlierudolph/coffeelint-alphabetize-keys#3]
@charlierudolph Do you think it would be valuable to support an option for specific overrides? For example, when writing React components, there is argument for ordering the lifecycle methods within a specific order (componentWillMount before componentDidMount, for example).

**Comment by charlierudolph** [comment]
Hmm interesting. Yeah I would be fine supporting that. 

So right now, we have 6 category of keys that must be alphabetical within the category. The user could essentially just be adding a new category of keys and if a key fits into a user defined category, then it is removed from its default category.

**Comment by charlierudolph** [comment]
Published in `1.5.0`
